import React from 'react';
import { connect } from 'react-redux';
import { hashHistory } from 'react-router';
import { Notification } from 'react-notification';

import QuestionList from './QuestionList';


const { array, func, number, string } = React.PropTypes;


/*
 * The QuizForm component
 *
 * @todo: Need to display question type based on question type
 *
 * @since 2.0.0
 */

const QuizForm = React.createClass({
  propTypes: {
    userAnswers: array,
    numAttempts: number,
    courseName: string,
    lessons: array,
    questions: array,
    incrementNumAttempts: func,
    resetQuiz: func
  },


  /*
   * Set the initial state of the component
   *
   * @since 1.0.0
   */

  getInitialState() {
    return {
      isNotificationActive: false,
      message: 'Please answer all the questions'
    };
  },


  /*
   * Set whether the notification is active in state
   *
   * @since 1.0.0
   */

  toggleNotification() {
    this.setState({ isNotificationActive: !this.state.isNotificationActive });
  },


  /*
   * Check if each question has answer
   *
   * @since 1.0.0
   */

  isAllAnswered() {
    return Object.keys(this.props.userAnswers).length === this.props.questions.length;
  },


  /*
   * Add an 'incorrect' and 'correct' class to an element
   *
   * @param {String} id - The html element's id
   * @param {String} cls - The html class to add to the element
   *
   * @since 1.0.0
   */

  showCorrectIndicator(id, cls) {
	  const el = document.getElementById(id);

		el.classList.remove('incorrect');
		el.classList.remove('correct');
		el.classList.add(cls);
  },


  /*
   * Generate a link
   *
   * @param {String} url - A relative url from the root element's exit-page data attribute
   * @param {Object} [params] - Option url parameters
   *
   * @return {String} url - An absolute url to redirect after the quiz completes successfully
   *
   * @since 1.0.0
   */

  generateLink(url, params={}) {
    const esc = encodeURIComponent;
    let query;
    let a;

    // Generate the query string
    if (params) {
      query = Object.keys(params).map(k => esc(k) + '=' + esc(params[k])).join('&');
    }

    // Build the url and return it
    return ((url) => {
      (!a) ? a = document.createElement('a') : a;
      a.href = `${ url }?${ query }`;
      return a.href;
    })(url);
  },


  /*
   * Generate the link to the page a user should be redirected to after successfully completing the quiz
   *
   * @see https://github.com/IIP-Design/wp-simple-nonce
   *
   * @return {String} - The absolute url
   *
   * @since 1.0.0
   */

  generateExitLink() {
    const url = document.getElementById('course-container').getAttribute('data-exit-page');
    let params = { course: this.props.courseName };

    // The token object is generated by the wp-simple-nonce plugin.
    if (typeof token !== 'undefined') {
      if ('name' in token && 'value' in token) {
        params.tokenName = token.name;
        params.tokenValue = token.value;
      }
    }

    return this.generateLink(url, params);
  },


  /*
   * Redirect the user to the exit page
   *
   * @since 1.0.0
   */

  goToCertificateScreen() {
    const exitPage = this.generateExitLink();
   	window.location = exitPage;
  },


  /*
   * Filter correct question choices
   *
   * @param {Object} choice - A choice from a question.choices array
   *
   * @return {Object} choice - Return a choice that matches the condition
   *
   * @since 2.0.0
   */

  isCorrectFilter(choice) {
    return choice.correct === true
  },


  /*
   * Get an array of correct answers
   *
   * @param {Array} questions - An array of questions
   *
   * @return {Array} correctAnswers - An array of correct answers
   *
   * @since 2.0.0
   */

  getCorrectAnswers(questions) {
    // Get a flat array of all the questions' choices
    const choices = [].concat.apply([], questions.map(question => question.choices));

    // Return only the filtered choices
    return choices.filter(this.isCorrectFilter);
  },


  /*
   * Compare the correct answers with the user's answers
   *
   * @return {Array} results - An array of correct answers
   *
   * @since 2.0.0
   */

  scoreQuiz() {
    const questions = this.props.questions;
    const userAnswers = this.props.userAnswers;
    const correctAnswers = this.getCorrectAnswers(questions);
    const results = [];

    userAnswers.forEach(answer => {

      // Set it to incorrect initally
      this.showCorrectIndicator(answer.questionId, 'incorrect');

      correctAnswers.forEach(correct => {

        // If the answer and correct answer match, mark it correct and push it to the results array
        if (correct.id === answer.choiceId) {
          this.showCorrectIndicator(answer.questionId, 'correct');
          results.push(answer);
        }
      });
    });

    return results;
  },


  /*
   * Respond to the form's onSubmit event
   *
   * @param {Object} event - The event object
   */

  handleSubmit(e) {
  	e.preventDefault();

    // This should always be one less than the number of actual max attempts because it starts at zero
    const maxAttempts = 4;

		// All questions not answerecd, show notification
		if(!this.isAllAnswered()) {
		  this.setState({ message: 'Please answer all the questions' });
			this.toggleNotification();
		}

		// All questions answered correctly, send to cert screen
		else if (this.scoreQuiz().length === this.props.questions.length)  {
      this.goToCertificateScreen();
		}

		// User got some wrong
		else {

      // If max attempts reached, redirect to first lesson
      if( this.props.numAttempts === maxAttempts ) {
        this.props.resetQuiz();
				hashHistory.push(`/lesson/${this.props.lessons[0].slug}`);

      // Else notify user of mistakes
			} else {
        this.props.incrementNumAttempts();
			  this.setState({
					message: 'Some of your answers are incorrect, please try again' ,
				});
				this.toggleNotification ();
			}
		}
  },


  /*
   * Render the component
   *
   * @todo: Activate submit button if num answers is the same as num questions
   * @todo: Ensures all questions have been answered
   */

  render() {
    const props = this.props;

    return (
      <div>
        <form id='formQuiz' onSubmit={ this.handleSubmit }>
          <div className='quiz-agrmt'>Certificate Agreement <span className='quiz-required'>*</span></div>
          <label htmlFor='certify'>
            <input id='certify' type={'checkbox'} name='certify'/>
            I certify that I have taken all the lessons related to this quiz before obtaining the certificate.
          </label>
          <QuestionList questions={ this.props.questions }/>
          <input type="submit" value="Submit and Get Certificate" />
        </form>
        <Notification
          isActive={ this.state.isNotificationActive }
          message={ this.state.message }
          action='Dismiss'
          onDismiss={ this.toggleNotification }
          dismissAfter = { 3500 }
          onClick={() =>  this.setState({ isNotificationActive: false })}
        />
      </div>
    );
  }
});


export default QuizForm;

